services:
#    bds_chat.example:
#        class: BDS\ChatBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    bds_chat.manager:
        class: BDS\ChatBundle\Manager\ChatManager
        arguments: [ @doctrine.orm.entity_manager ]
