<?php

namespace BDS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarracteristiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarracteristiqueRepository extends EntityRepository
{
}
