services:
#    bds_sponsor.example:
#        class: BDS\SponsorBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    bds_sponsor.manager:
        class:      BDS\SponsorBundle\Manager\SponsorManager
        argument:   [ @doctrine.orm.entity_manager ]
