<?php

namespace BDS\CalendrierBundle\Entity;

/**
 * CalendrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierRepository extends \Doctrine\ORM\EntityRepository
{
}
