services:
#    bds_user.example:
#        class: BDS\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    bds_membre.manager:
        class:        BDS\UserBundle\Manager\MembreManager
        arguments:    [ @doctrine.orm.entity_manager, @security.context ]
        
    bds_user.manager:
        class:        BDS\UserBundle\Manager\UserManager
        arguments:    [ @doctrine.orm.entity_manager, @security.context ]
    
    app.form.profile:
        class:        BDS\UserBundle\Form\UserEditType
        tags:
            - { name: form.type, alias: bds_user_edit }