services:
#    bds_user.example:
#        class: BDS\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    bds_membre.manager:
        class:        BDS\UserBundle\Manager\MembreManager
        arguments:    [ @doctrine.orm.entity_manager, @security.context ]